Feature/ux enhancements - Resolved #51
Bashamega/TrendTrack pull request #54
Opened 2024-10-03 22:36 UTC by clydehenry3

## Description

### Summary of Changes:
This update introduces a new hero section with custom content and ux/design improvements. The navigation bar has been updated to include the logo, and a custom hero image has been added to enhance the visual appeal of the landing page.

### Related Issue:
This change addresses [Issue #51 ], which requested the addition of a hero section and logo placement in the navigation bar. _**Please see Line 26 in src/components/Hero.tsx to link sections together. Attempted to add a smooth scroll but it kept breaking the file.**_

### Motivation and Context:
The purpose of these updates is to improve the user interface by making the landing page more visually engaging and providing clear branding through the logo and custom imagery in the hero section.

### Dependencies:
No new dependencies were added as part of this update. Tailwind CSS was used to style the components.

Fixes #(issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable):
<img width="1440" alt="TrendTrack After" src="https://github.com/user-attachments/assets/f5ff6e0a-3a90-4745-9fd6-748f90140fca">

2024-10-03 22:41 UTC, clydehenry3 commented
@Bashamega Testing worked great on my machine. Is there anything within my code to improve it? Thanks.

2024-10-04 03:22 UTC, Bashamega commented
> @Bashamega Testing worked great on my machine. Is there anything within my code to improve it? Thanks.

The error is with linter:
```
22:73  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
```

2024-10-04 03:23 UTC, Bashamega requested changes

2024-10-04 03:23 UTC, Bashamega commented on src/assets/Logo.svg
use the second icon

2024-10-04 03:23 UTC, Bashamega commented on src/components/Hero.tsx
> +            in one user-friendly place. Stay u`pdated daily and see what's
fix linter and fix spelling
```suggestion
            in one user-friendly place. Stay updated daily and see what&apos;s
```

2024-10-04 06:20 UTC, Bashamega requested changes

2024-10-04 06:20 UTC, Bashamega commented on src/assets/Logo.svg
I mean this icon: 
![image](https://github.com/user-attachments/assets/a8daffe4-b127-4259-8949-e51a0b9e3118)

2024-10-04 06:20 UTC, Bashamega commented on src/components/Nav.tsx
>      <nav className="bg-gray-800 p-4 w-screen">
```suggestion
    <nav className="bg-gray-800 p-4">
```

2024-10-04 06:24 UTC, Bashamega commented
Also please fix the responsivness

2024-10-04 19:19 UTC, clydehenry3 commented
> Also please fix the responsivness

I believe the responsive issue is within the cards or the viewport themselves. When using the dev tools and making the screen smaller, it responds great. However when using just the browser, it appears to be within the cards being too wide.

2024-10-04 19:19 UTC, clydehenry3 commented
I have made the changes of spelling, symbols, and logo.

2024-10-05 02:15 UTC, Bashamega approved these changes
Great work !

2024-10-05 02:16 UTC, merged

2024-10-05 15:56 UTC, clydehenry3 commented
I'm also going to upload the hero image because when looking on my phone, it looks blurry even though it's an SVG. Going to see how I can improve this.