enhancement: make hover smooth
Bashamega/TrendTrack pull request #65
Opened 2024-10-08 17:54 UTC by shobhit15082003

## Description

Made the hover smooth.

Fixes #64 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable):

https://github.com/user-attachments/assets/953fbc1f-4000-4d00-b596-7bef30e27bdc

2024-10-08 18:19 UTC, shobhit15082003 commented
@Bashamega if you want to make the delay greater plz let me know

2024-10-09 03:35 UTC, Bashamega requested changes

2024-10-09 03:35 UTC, Bashamega commented on package-lock.json
> +      "version": "0.15.0",
```suggestion
      "version": "0.14.0",
```

2024-10-09 03:35 UTC, Bashamega approved these changes
great work

2024-10-09 03:35 UTC, merged